/**
 * Sample project
 * My sample API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    createdAt?: string;
    updatedAt?: string;
}

