openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Users definitions"
  description: "Demonstrate Users definitions"
paths:
  /users:
    get:
      description: "List users"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
    post:
      summary: "Create user"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
