openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Clients definitions"
  description: "Demonstrate Clients definitions"
paths:
  /clients:
    get:
      description: "List clients"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
    post:
      summary: "Create client"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
